---
- name: download oc
  get_url:
    url: https://github.com/openshift/origin/releases/download/v3.9.0/openshift-origin-client-tools-v3.9.0-191fece-linux-64bit.tar.gz
    dest: "{{ dest_folder }}"

- name: unzip oc
  unarchive:
    src: "{{ dest_folder }}/openshift-origin-client-tools-v3.9.0-191fece-linux-64bit.tar.gz"
    dest: "{{ dest_folder }}"

- name: export Path with oc
  copy:
    dest: /etc/profile.d/oc-path.sh
    content: 'PATH=$PATH:{{ dest_folder }}'